using System;

namespace DataSync.Core.Models
{
    /// <summary>
    /// One row of the TProcessData table. Every public property is a column: reads map columns to properties by
    /// name, and <see cref="Data.SqlProcessDataStore.SaveBatch"/> builds its column list from them, so a new column
    /// needs only a property.
    /// </summary>
    public class TProcessData
    {
        public long BaseID { get; set; }
        public DateTime DateTimeRecord { get; set; }
        public double WOH { get; set; }
        public double SPP { get; set; }
        public double TorqueTD { get; set; }
        public double RPMTD { get; set; }
        public double Pit11 { get; set; }
        public double Pit12 { get; set; }
        public double AnnPr { get; set; }
        public double FlowOut { get; set; }
        public double TorqueRT { get; set; }
        public double SA1 { get; set; }
        public double CMD_HBrake { get; set; }
        public double CMD_Aclrt { get; set; }
        public double CMD_Tt_RPM { get; set; }
        public double CMD_Tt_Tq_Lmt { get; set; }
        public double CMD_Tt_RT { get; set; }
        public double CMD_Tt_ToTQ { get; set; }
        public double Pit1 { get; set; }
        public double Pit2 { get; set; }
        public double Pit3 { get; set; }
        public double Pit4 { get; set; }
        public double Pit5 { get; set; }
        public double Pit6 { get; set; }
        public double Pit7 { get; set; }
        public double Pit8 { get; set; }
        public double Pit9 { get; set; }
        public double Pit10 { get; set; }
        public double TempIn { get; set; }
        public double TempOut { get; set; }
        public double MWInUp { get; set; }
        public double MWInDown { get; set; }
        public double MWOutUp { get; set; }
        public double MWOutDown { get; set; }
        public double SA2 { get; set; }
        public double SA3 { get; set; }
        public double SA4 { get; set; }
        public double SA5 { get; set; }
        public double SA6 { get; set; }
        public double SA7 { get; set; }
        public double SA8 { get; set; }
        public double SA9 { get; set; }
        public double CMD_Brake { get; set; }
        public double SDI1 { get; set; }
        public double SDI2 { get; set; }
        public double SDI3 { get; set; }
        public double SDI4 { get; set; }
        public double SDI5 { get; set; }
        public double SDI6 { get; set; }
        public double SDI7 { get; set; }
        public double HookPos { get; set; }
        public double RpmRT { get; set; }
        public double SPuls1 { get; set; }
        public double SPM1 { get; set; }
        public double SPM2 { get; set; }
        public double SPM3 { get; set; }
        public double Spare { get; set; }
        public double WellDepth { get; set; }
        public double BitDepth { get; set; }
        public double WOB { get; set; }
        public double LagDepth { get; set; }
        public double LagTime { get; set; }
        public double Gain { get; set; }
        public double Overpull { get; set; }
        public double Drag { get; set; }
        public double Loss { get; set; }
        public double HookAccelerator { get; set; }
        public double HookShift { get; set; }
        public double HookVelocity { get; set; }
        public double AnnularVolume { get; set; }
        public double LineWork { get; set; }
        public double FollowIn1 { get; set; }
        public double FollowIn2 { get; set; }
        public double FollowIn3 { get; set; }
        public double FollowIn { get; set; }
        public double TotalStrock { get; set; }
        public double TStork1 { get; set; }
        public double TStork2 { get; set; }
        public double TStork3 { get; set; }
        public double ActVol1 { get; set; }
        public double ActCap1 { get; set; }
        public double ActPercent1 { get; set; }
        public double ActVol2 { get; set; }
        public double ActCap2 { get; set; }
        public double ActPercent2 { get; set; }
        public double PtVol11 { get; set; }
        public double PtVol12 { get; set; }
        public double PtVol1 { get; set; }
        public double PtVol2 { get; set; }
        public double PtVol3 { get; set; }
        public double PtVol4 { get; set; }
        public double PtVol5 { get; set; }
        public double PtVol6 { get; set; }
        public double PtVol7 { get; set; }
        public double PtVol8 { get; set; }
        public double PtVol9 { get; set; }
        public double PtVol10 { get; set; }
        public double PTFLevel11 { get; set; }
        public double PTFLevel12 { get; set; }
        public double PTFLevel1 { get; set; }
        public double PTFLevel2 { get; set; }
        public double PTFLevel3 { get; set; }
        public double PTFLevel4 { get; set; }
        public double PTFLevel5 { get; set; }
        public double PTFLevel6 { get; set; }
        public double PTFLevel7 { get; set; }
        public double PTFLevel8 { get; set; }
        public double PTFLevel9 { get; set; }
        public double PTFLevel10 { get; set; }
        public double PitPecent11 { get; set; }
        public double PitPecent12 { get; set; }
        public double PitPecent1 { get; set; }
        public double PitPecent2 { get; set; }
        public double PitPecent3 { get; set; }
        public double PitPecent4 { get; set; }
        public double PitPecent5 { get; set; }
        public double PitPecent6 { get; set; }
        public double PitPecent7 { get; set; }
        public double PitPecent8 { get; set; }
        public double PitPecent9 { get; set; }
        public double PitPecent10 { get; set; }
        public double PTCap11 { get; set; }
        public double PTCap12 { get; set; }
        public double PTCap1 { get; set; }
        public double PTCap2 { get; set; }
        public double PTCap3 { get; set; }
        public double PTCap4 { get; set; }
        public double PTCap5 { get; set; }
        public double PTCap6 { get; set; }
        public double PTCap7 { get; set; }
        public double PTCap8 { get; set; }
        public double PTCap9 { get; set; }
        public double PTCap10 { get; set; }
        public double PTArea11 { get; set; }
        public double PTArea12 { get; set; }
        public double PTArea1 { get; set; }
        public double PTArea2 { get; set; }
        public double PTArea3 { get; set; }
        public double PTArea4 { get; set; }
        public double PTArea5 { get; set; }
        public double PTArea6 { get; set; }
        public double PTArea7 { get; set; }
        public double PTArea8 { get; set; }
        public double PTArea9 { get; set; }
        public double PTArea10 { get; set; }
        public double TMudP { get; set; }
        public double MudP1 { get; set; }
        public double MudP2 { get; set; }
        public double MudP3 { get; set; }
        public double MWIn { get; set; }
        public double MWOut { get; set; }
        public double DiffTemp { get; set; }
        public double RigStatus { get; set; }
        public double BHAStatus { get; set; }
        public double TDStatus { get; set; }
        public double HookStatus { get; set; }
        public double AutoStatus { get; set; }
        public double ReamingMode { get; set; }
        public double HRPump1 { get; set; }
        public double HRPump2 { get; set; }
        public double HRPump3 { get; set; }
        public double HRTD { get; set; }
        public double HRRT { get; set; }
        public double HRBit { get; set; }
        public double Rop2 { get; set; }
        public double RPM { get; set; }
        public double Torque { get; set; }
        public double Tcirculation { get; set; }
        public double SuToBottom { get; set; }
        public double ActVol3 { get; set; }
        public double ActVol4 { get; set; }
        public double ActCap3 { get; set; }
        public double ActCap4 { get; set; }
        public double ActPercent3 { get; set; }
        public double ActPercent4 { get; set; }
        public double StringWeight { get; set; }
        public double DiffFlow { get; set; }
        public double DrillingCount { get; set; }
        public double Wohoffslips { get; set; }
        public double WohoffBottom { get; set; }
        public double MPNS1 { get; set; }
        public double MPNS2 { get; set; }
        public double MPNS3 { get; set; }
        public double TotalMPNS { get; set; }
        public double TMPS1 { get; set; }
        public double TMPS2 { get; set; }
        public double TMPS3 { get; set; }
        public double TMPS { get; set; }
        public double TotalSPM { get; set; }
        public double TotalTripTnk { get; set; }
        public double TotalPit { get; set; }
        public double ROP5Cm { get; set; }
        public double ROP20Cm { get; set; }
        public double ROP100Cm { get; set; }
        public double ROP5Min { get; set; }
        public double ROP20Min { get; set; }
        public double ROP60Min { get; set; }
        public double StripDepth { get; set; }
    }
}